public  class ArthimaticCalculations {
    // added new text
        public void addition ( integer x, integer y) {
        integer z = x+y;
        system.debug(' sum of ' + x + ' and ' + y + ' is ' + z);

    }

        public void subtraction  ( integer x, integer y){
            integer z = x - y;
            system.debug( ' sub of ' + x + ' and ' + y + ' is ' + z);
        }

        public void multiplication  (integer x, integer y) {
            integer z = x*y;
            system.debug(' multi of ' + x + ' and ' + y + ' is ' + z);

        }
}